import { z } from "zod";

import { errorResponse, successResponse } from "@/lib/server/api-response";
import { auth } from "@/lib/server/auth";
import { getBillingStatus } from "@/lib/server/billing";
import { analyzeTradeIdea } from "@/lib/server/gemini";
import { rateLimit } from "@/lib/server/rate-limit";

export const dynamic = "force-dynamic";

// Premium feature: real AI analysis of a trade idea, generated by Gemini
// with strict grounding rules (see lib/server/gemini.ts). Rate-limited per
// user per day to bound AI API costs.

const analyzeSchema = z.object({
  ticker: z.string().trim().min(1).max(12),
  company: z.string().trim().max(200).default(""),
  direction: z.string().trim().max(60).default(""),
  timeframe: z.string().trim().max(60).default(""),
  technicalEvidence: z.string().trim().max(2000).default(""),
  fundamentalEvidence: z.string().trim().max(2000).default(""),
  catalystEvidence: z.string().trim().max(2000).default(""),
  assumptions: z.string().trim().max(2000).default(""),
  risk: z.string().trim().max(2000).default(""),
  invalidation: z.string().trim().max(2000).default(""),
});

export async function POST(request: Request) {
  const session = await auth();
  const userId = session?.user?.id;
  if (!userId) {
    return errorResponse("UNAUTHORIZED", "Sign in to use the AI Analyst.", {
      status: 401,
    });
  }

  const billing = await getBillingStatus(userId);
  if (!billing.premium) {
    return errorResponse(
      "PAYMENT_REQUIRED",
      "The AI Analyst is a Premium feature. Subscribe to unlock real AI analysis.",
      { status: 402 },
    );
  }

  if (!rateLimit(`analyst:${userId}`, 20, 24 * 60 * 60 * 1000)) {
    return errorResponse(
      "RATE_LIMITED",
      "Daily AI analysis limit reached (20/day). Try again tomorrow.",
      { status: 429 },
    );
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return errorResponse("VALIDATION_ERROR", "Request body must be JSON.", {
      status: 400,
    });
  }

  const parsed = analyzeSchema.safeParse(body);
  if (!parsed.success) {
    return errorResponse("VALIDATION_ERROR", "Invalid analysis request.", {
      status: 400,
    });
  }

  if (!process.env.GEMINI_API_KEY) {
    return errorResponse(
      "INTERNAL_ERROR",
      "The AI engine is not configured yet. Please try again later.",
      { status: 503 },
    );
  }

  try {
    const analysis = await analyzeTradeIdea({
      ...parsed.data,
      ticker: parsed.data.ticker.toUpperCase(),
    });
    return successResponse({
      ...analysis,
      generatedAt: new Date().toISOString(),
      model: process.env.GEMINI_MODEL ?? "gemini-2.5-flash",
    });
  } catch (error) {
    console.error("AI Analyst failed:", error);
    return errorResponse(
      "INTERNAL_ERROR",
      error instanceof Error
        ? error.message
        : "The AI engine could not complete the analysis.",
      { status: 500 },
    );
  }
}
